import QueryProvider from "@/components/QueryProvider";
import AuthProvider from "../components/AuthProvider";
import { Roboto } from "next/font/google";
import { Toaster } from "@/components/Toaster";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} flex h-screen flex-col bg-gray-50`}>
        <AuthProvider>
          <QueryProvider>{children}</QueryProvider>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
